Resources:
  RecipeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RecipeTable
      AttributeDefinitions:
        - AttributeName: recipeId
          AttributeType: N
      KeySchema:
        - AttributeName: recipeId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  IngredientTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: IngredientTable
      AttributeDefinitions:
        - AttributeName: ingredientId
          AttributeType: N
        - AttributeName: recipeId
          AttributeType: N
      KeySchema:
        - AttributeName: ingredientId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: recipeIndex
          KeySchema:
            - AttributeName: recipeId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
